version: '3.8'

services:
    
    mailhog:
        container_name: ${COMPOSE_PROJECT_NAME}_mailhog
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mailhog.rule=Host(`mailhog.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
            - "traefik.port=80"
            
    mariadb:
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb
        image: mariadb:10.8.3
        hostname: mariadb
        volumes:
        - ./data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}_mariadb.rule=HostSNI(`mariadb.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.tcp.routers._mariadb.service=mariadb-svc"
            - "traefik.tcp.services._mariadb-svc.loadbalancer.server.port=3306"
            
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin:5.2.0
        hostname: phpmyadmin
        environment:
            - PMA_HOSTS=mariadb,mariadb-basic.mariadb.database.azure.com
            - UPLOAD_LIMIT=2000M
        depends_on:
            - mariadb
        volumes:
            - /sessions
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_phpmyadmin.rule=Host(`phpmyadmin.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.port=80"
    
    ftpserver:
        container_name: ${COMPOSE_PROJECT_NAME}_ftpserver
        image: stilliard/pure-ftpd:latest
        hostname: ftpserver
        volumes:
            - ../:/home
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        environment:
            PUBLICHOST: "localhost"
            FTP_USER_NAME: "ftpuser"
            FTP_USER_PASS: "ftppass"
            FTP_USER_HOME: "/home"

    app_redis:
        container_name: ${COMPOSE_PROJECT_NAME}_app_redis
        image: redis:7.0.4-alpine
        hostname: app_redis

    redis_admin:
        container_name: ${COMPOSE_PROJECT_NAME}_redis_admin
        hostname: phpredisadmin
        image: erikdubbelboer/phpredisadmin:latest
        depends_on:
            - app_redis
        environment:
            - REDIS_1_HOST=app_redis
            - REDIS_1_NAME=app_redis
            - REDIS_2_HOST=phcomm-app.redis.cache.windows.net
            - REDIS_2_NAME=azure
            - REDIS_2_PORT=6379
            - REDIS_2_AUTH=OLKKQ12ey9kacoFPRRlah5AkQh64Qdy8x5mSsbDqTeU=
            - REDIS_2_DATABASES=4
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_redis_admin.rule=Host(`redis_admin.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.port=80"
               